export const states = [
  { state: "Andhra Pradesh", code: "AP" },
  { state: "Arunachal Pradesh", code: "AR" },
  { state: "Assam", code: "AS" },
  { state: "Bihar", code: "BR" },
  { state: "Chhattisgarh", code: "CG" },
  { state: "Goa", code: "GA" },
  { state: "Gujarat", code: "GJ" },
  { state: "Haryana", code: "HR" },
  { state: "Himachal Pradesh", code: "HP" },
  { state: "Jharkhand", code: "JH" },
  { state: "Karnataka", code: "KA" },
  { state: "Kerala", code: "KL" },
  { state: "Madhya Pradesh", code: "MP" },
  { state: "Maharashtra", code: "MH" },
  { state: "Manipur", code: "MN" },
  { state: "Meghalaya", code: "ML" },
  { state: "Mizoram", code: "MZ" },
  { state: "Nagaland", code: "NL" },
  { state: "Odisha", code: "OD" },
  { state: "Punjab", code: "PB" },
  { state: "Rajasthan", code: "RJ" },
  { state: "Sikkim", code: "SK" },
  { state: "Tamil Nadu", code: "TN" },
  { state: "Telangana", code: "TG" },
  { state: "Tripura", code: "TR" },
  { state: "Uttar Pradesh", code: "UP" },
  { state: "Uttarakhand", code: "UK" },
  { state: "West Bengal", code: "WB" }
];
